version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - redis-net
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=redis
    ports:
      - 8081:8081
    networks:
      - redis-net

networks:
  redis-net:

volumes:
  redis-data:
